### ISSUE TITLE
Создание локального слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgismobile_android#14]
В приложении должна поддерживаться возможность создания локального пользовательского векторного слоя. Пользователь должен указывать тип геометрии слоя, типы и наименования полей атрибутивных данных, значения полей по-умолчанию, требование по вводу данных (не нулевые поля).

**Comment by 4eRTuk** [comment]
Added in e9759b50d8250d3d5abc5623b786d1b19d4da9f7
