### ISSUE TITLE
Добавить регистрацию/вход

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgismobile_android#2]
Также приложение должно предлагать зарегистрироваться или авторизоваться в [my.nextgis.com](https://my.nextgis.com/). Пользователь должен иметь возможность отказаться от авторизации и пройти авторизацию позже через настройки приложения.

**Comment by 4eRTuk** [comment]
Impolemented in e93a1bb2765a1f7279b8db8fb574b5614f767244
